--- # 数据源配置
spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${datasource.uac.url}
  username: ${datasource.uac.username}
  password: ${datasource.uac.password}
    
jwt:
  secret-key: ${uac.name}-abcdefghijklmnopqrstuvwxyz
  expire-time: 43200000 # 12 小时
  refresh-time: 7200000 # token 过期前多少毫秒刷新 token (2小时)

--- # 监控中心配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: true
  instance:
    name: UAC Platform
    service-host-type: IP

spring.cloud:
  sentinel:
    datasource:
      flow-rule:
        nacos:
          server-addr: ${spring.cloud.nacos.server-addr}
          username: ${spring.cloud.nacos.username}
          password: ${spring.cloud.nacos.password}
          group-id: ${spring.cloud.nacos.config.group}
          namespace: ${spring.cloud.nacos.config.namespace}
          data-id: ${spring.application.name}-flow-rules.json
          data-type: json
          rule-type: flow

# security 配置
security:
  enabled: true
  # 排除路径
  excludes:
    # 认证路径
    - /
    - /auth/**
    - /ids/**
    # 静态资源
    - /**.html
    - /**.css
    - /**.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**
    - /ai/**
    - /demo/**

# springdoc 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  info:
    title: UAC 平台
    description: 提供管理后台、用户 App 的所有功能
    version: ${uac.version}

--- # Actuator 监控端点的配置项
management:
  endpoint:
    logfile:
      external-file: ./logs/${uac.name}-error.log # Spring Boot Admin 在线查看日志的路径，与 logback-plus.xml 里生成的文件路径一致，这里取得是 error 的日志

# 用户配置
login:
  fail:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# 多租户配置
tenant:
  enable: true
  excludes-table:
    - t_sys_client
    - t_sys_tenant

# 默认配置
default:
  password: 123456 # 新用户的默认密码

# 数据加密
mybatis-encryptor:
  # 是否开启加密
  enable: true
  # 加密实体类包路径
  class-package: cn.youngkbt.uac.demo

# api 接口加密
api-decrypt:
  # 是否开启全局接口加密
  enabled: true

--- # websocket
websocket:
  # 如果关闭，需要和前端开关一起关闭
  enabled: true
  # 路径
  path: /uac/websocket
  